/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */

// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  // tutorialSidebar: [{type: 'autogenerated', dirName: '.'}],

  // But you can create a sidebar manually

  doc: [
    'overview',
    {
      'Getting started': [
        'get-started/quick-start',
        'get-started/install'
      ],
    },
    {
      Scenarios: [
        'scenarios/image-deduplication',
        'scenarios/music-recognition-system',
        'scenarios/reverse-image-search',
      ],
    },
    {
      'Supported pipelines': [
        'pipelines/image-embedding',
        'pipelines/music-embedding',
      ],
    },
    {
      'Supported operators': [
        'operators/image-loading-and-transforms',
        'operators/model-based-operators',
      ],
    },
    {
      'Dive deep': [
        'dive-deep/pipeline-config',
        'dive-deep/hub-integration-and-caching',
        'dive-deep/frequent-errors',
        'dive-deep/contributing-guide',
      ],
    },
    {
      Develop: [
        {
          Framework: [
            'develop/framework/architectural-overview',
            'develop/framework/DAG-details',
            'develop/framework/engine-details',
          ],
        },
        {
          Layer: [
            'develop/layer/layer-introduction',
            'develop/layer/layer-details',
          ],
        },
        'develop/image-ensemble-training',
        'develop/roadmap',
      ],
    },
  ],
};

module.exports = sidebars;
