/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */

// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  // tutorialSidebar: [{type: 'autogenerated', dirName: '.'}],

  // But you can create a sidebar manually

  doc: [
    {
      type: 'category',
      label: 'Introduction',
      items: ['introduction/towhee-philosophy'],
    }, {
      type: 'category',
      label: 'Getting started',
      items: ['get-started/install', 'get-started/first-pipeline']
    }, {
      type: 'category',
      label: 'Scenarios',
      items: [
        'scenarios/image-deduplication',
        'scenarios/music-recognition-system',
        'scenarios/reverse-image-search'
      ]
    }, {
      type: 'category',
      label: 'Supported pipelines',
      items: [
        'pipelines/image-embedding',
        'pipelines/music-embedding'
      ]
    }, {
      type: 'category',
      label: 'Supported operators',
      items: [
        'operators/image-loading-and-transforms',
        'operators/model-based-operators'
      ]
    }, {
      type: 'category',
      label: 'Dive deep',
      items: [
        'dive-deep/pipeline-config',
        'dive-deep/hub-integration-and-caching',
        'dive-deep/frequent-errors',
        'dive-deep/contributing-guide'
      ]
    }, {
      type: 'category',
      label: 'Develop',
      items: [{
        type: 'category',
        label: 'Framework',
        items: [
          'develop/framework/architectural-overview',
          'develop/framework/DAG-details',
          'develop/framework/engine-details'
        ]
      }, {
        type: 'category',
        label: 'Layer',
        items: [
          'develop/layer/layer-introduction',
          'develop/layer/layer-details'
        ]
      },
      'develop/image-ensemble-training',
      'develop/roadmap'
      ]
    }
  ],

};

module.exports = sidebars;
